# Universal Windows Platform
# Build a Universal Windows Platform project using Visual Studio.
# Add steps that test and distribute an app, save build artifacts, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - feature/*
    - fix/*

pool:
  vmImage: 'windows-2022'

variables:
  group: BuildPipelineVariables
  solution: '**/FolderIconPainter.sln'
  testProject: '**/*.UnitTests.csproj'
  xUnitTestProject: '**/FIP.Core.xUnitTests.csproj'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'
  appxPackageDir: '$(build.artifactStagingDirectory)\AppxPackages\\'
  buildFolder: '$(Build.SourcesDirectory)\bin\'
  
jobs:
- job: Build
  displayName: 'Build & Run Tests'
  timeoutInMinutes: 10
  steps:
  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    displayName: Restore NuGet Packages for Folder Icon Painter 
    inputs:
      command: 'restore'
      restoreSolution: '$(solution)'

  - task: VSBuild@1
    displayName: 'Build Folder Icon Painter Package'
    inputs:
      platform: '$(buildPlatform)'
      solution: '$(solution)'
      configuration: '$(buildConfiguration)'
      msbuildArgs: '/p:AppxBundlePlatforms="$(buildPlatform)" 
                    /p:AppxPackageDir="$(appxPackageDir)"
                    /p:AppxPackageSigningEnabled=false 
                    /p:AppxBundle=Always 
                    /p:GenerateAppxPackageOnBuild=true
                    /p:PublishReadyToRun=false'

# Builds unit tests
  - task: MSBuild@1
    displayName: 'Build Unit Tests'
    inputs:
      solution: '$(testProject)'
      platform: '$(buildPlatform)'
      configuration: 'Debug'
      msbuildArguments: '/t:build /restore'
      maximumCpuCount: true

  - task: Windows Application Driver@0
    displayName: Start Windows Application Driver
    inputs:
      OperationType: "Start"
      AgentResolution: "1080p"

  - task: VSTest@2
    displayName: 'Run UI Tests'
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: |
        **\bin\$(buildPlatform)\Debug\**\*UnitTests.dll
        !**\*TestAdapter.dll
        !**\obj\**
        !**\ref\**
      searchFolder: '$(System.DefaultWorkingDirectory)'
      resultsFolder: '$(Build.ArtifactStagingDirectory)\TestResults'
      platform: '$(BuildPlatform)'
      configuration: 'Debug'
      minimumExpectedTests: 1
      failOnMinTestsNotRun: true
      codeCoverageEnabled: true

  - task: Windows Application Driver@0
    displayName: Stop Windows Application Driver
    inputs:
      OperationType: "Stop"
      condition: always()

  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    inputs:
      testResultsFormat: VSTest
      testResultsFiles: '**\*.trx'
      searchFolder: '$(Agent.TempDirectory)'
      failTaskOnFailedTests: true
      testRunTitle: 'Unit tests'

  - task: DotNetCoreCLI@2
    displayName: 'Run xUnit Tests'
    inputs:
      command: 'test'
      projects: '$(xUnitTestProject)'
      arguments: '--configuration Debug --logger trx --results-directory $(Agent.TempDirectory)/xUnitResults'

  - task: PublishTestResults@2
    displayName: 'Publish xUnit Test Results'
    inputs:
      testResultsFormat: VSTest
      testResultsFiles: '**\*.trx'
      searchFolder: '$(Agent.TempDirectory)/xUnitResults'
      failTaskOnFailedTests: true
      testRunTitle: 'xUnit tests'
